language: android
android:
  components:
    - build-tools-24.0.0
    - android-23
    - platform-tools
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-22

script: ./gradlew build

notifications:
  email:
    - caio.margutti.alves@gmail..com
    on_success: always
    on_failure: always