language: android

jdk:
  - oraclejdk7
  - openjdk7

android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

notifications:
  email: true

before_install:
    # Disable services enabled by default
    # http://docs.travis-ci.com/user/database-setup/#MySQL
    - sudo /etc/init.d/mysql stop
    - sudo /etc/init.d/postgresql stop

install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

script:
   - ./gradlew clean assembleDebug